# Generated by Django 4.1.5 on 2023-01-06 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_id', models.CharField(default=None, max_length=255, null=True)),
                ('type', models.CharField(max_length=255)),
                ('generated', models.BooleanField(default=False)),
                ('by', models.CharField(max_length=255, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField(max_length=500, null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('text', models.TextField(null=True)),
                ('score', models.BigIntegerField(default=0, null=True)),
            ],
            options={
                'ordering': ['-time', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('newsapp.base',),
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
            ],
            options={
                'ordering': ['-time', 'title'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('newsapp.base',),
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
                'ordering': ['-time', 'title'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('newsapp.base',),
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='newsapp.base')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_polloptions', to='newsapp.poll')),
            ],
            bases=('newsapp.base',),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='newsapp.base')),
                ('kids', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_comments', to='newsapp.comment')),
                ('poll', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poll_comments', to='newsapp.poll')),
                ('story', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='story_comments', to='newsapp.story')),
            ],
            bases=('newsapp.base',),
        ),
    ]
